site_name: GLM-HMM  # ← add this line

theme: material    # This theme is mandatory for now, see below

plugins:
  - gallery:
      examples_dirs: docs/tutorials          # path to scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
      # ... (other options)

  - search  # make sure the search plugin is still enabled

nav:
- Home: index.md
- Gallery: generated/gallery/index.md 