[project]
name = "glm-hmm-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "brainbox>=0.0.9",
    "ipykernel>=7.1.0",
    "ipympl>=0.10.0",
    "jupytext>=1.19.1",
    "matplotlib>=3.10.8",
    "mkdocs>=1.6.1",
    "numpy<=2.3.5",
    "seaborn>=0.13.2",
    "sphinx-autodoc-typehints>=3.10.2",
    "sphinx-contributors>=0.3.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-design>=0.7.0",
    "sphinx-togglebutton>=0.4.5",
]
